---

- name: 'set base_python_version: python2'
  set_fact:
    base_python_version: 'python2'
    base_python_package: 'python'
  tags:
    - python
    - pip

- name: 'install python_rpms from rhel repositories'
  become: yes
  when: ansible_os_family == 'RedHat'
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ python_rhel }}"
  tags:
    - python

- name: 'install python_rpms from epel repositories'
  become: yes
  when: ansible_os_family == 'RedHat'
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ python_epel }}"
  tags:
    - python
    - pip

#pip install setuptools --upgrade
#pip install pip --upgrade
#pip install -v ansible-container==0.3.0
